#pragma once

#define VENDOR_ID 0xFEED
#define PRODUCT_ID 0x0000
#define DEVICE_VER 0x0001
#define MANUFACTURER "Seojoon_Yeon"
#define PRODUCT "jason_split"

#define MATRIX_ROWS 6
#define MATRIX_COLS 6

#define MATRIX_ROW_PINS { GP3, GP4 }
#define MATRIX_COL_PINS { GP23, GP24, GP25 }

#define DIODE_DIRECTION ROW2COL

#define ENCODER_A_PINS { GP28 }
#define ENCODER_B_PINS { GP29 }
#define ENCODER_RESOLUTION 4

#define EE_HANDS
#define SPLIT_USB_DETECT

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_PIN_SWAP
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define DEBOUNCE 5
