#pragma once

#define MATRIX_ROW_PINS { GP3, GP4 }
#define MATRIX_COL_PINS { GP23, GP24, GP25 }

#define EE_HANDS
// #define SPLIT_USB_DETECT
// #define MASTER_LEFT


#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_PIN_SWAP
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define DEBOUNCE 5

#define ENCODER_A_PINS        { GP28 }
#define ENCODER_B_PINS        { GP29 }
#define ENCODER_A_PINS_RIGHT  { GP28 }
#define ENCODER_B_PINS_RIGHT  { GP29 }

#define ENCODER_RESOLUTIONS        { 4 }
#define ENCODER_RESOLUTIONS_RIGHT  { 4 }